### ISSUE TITLE
혹시 업데이트 되는 메일 혹은 다운받지 않은 메일만 백업하는 방법있나요?

### ISSUE THREAD

**Issue by folimm** [mdsnins/IZPM-Backup#1]
혹시 업데이트 되는 메일 혹은 다운받지 않은 메일만 백업하는 방법있나요?

덕분에 메일 백업 잘했습니다.

정말 감사해요.

한번 위즈원은 영원한 위즈원!! ^^

**Comment by mdsnins** [comment]
추후 기능 추가시 1순위로 생각하고 있는 기능이나 현생 문제가 ㅎㅎ;; 빠른 시일 내에 노력해보겠습니다^^

**Comment by folimm** [comment]
앗! 현생도 있으신데 ㅠ.ㅠ
감사합니다!

**Comment by mdsnins** [comment]
커밋 `e21ff87`에 반영되었고, 8시 25분경 izpm.wonyoung.kr 서버에 신규 적용되었습니다. 다시 한 번 스크립트 받아주시거나, 혹은 [pm.py](https://github.com/mdsnins/IZPM-Backup/blob/master/legacy/pm.py) 을 받아, pm_headers 만 기존 파일의 내용으로 교체해주시길 바랍니다.

**Comment by folimm** [comment]
무료 봉사에 ㅠ.ㅠ 이렇게 ㅠ.ㅠ 빠른 업데이트를... 감사합니다. 
그래도 오늘 아이즈원 유투브 / 트위터 / 프메 보면서 웃고 있네요 ^^
감사합니다 ^^
