### ISSUE TITLE
izpm.wonyoung.kr proxy not working

### ISSUE THREAD

**Issue by rootadminaccess** [mdsnins/IZPM-Backup#12]
izpm proxy 수동설정이후 http://private.mail 접속이 되지 않습니다.
포트나 도메인설정의 문제는 아니고 서버문제 같습니다

**Comment by mdsnins** [comment]
Okay, I restarted the server.
Please check it again

**Comment by rootadminaccess** [comment]
![Screenshot_20210510-233313_Certificate installer.jpg](https://user-images.githubusercontent.com/72973521/117676128-3aaedf00-b1e8-11eb-891a-0407e976c5c6.jpg)

이제는
프록시 설정 후 http://private.mail 접속 이후
안드로이드 인증서 설치 후
.cer로 확장자 변경이후 설치하려니
사진과 같은 에러가 발생합니다.
(안드로이드 버젼 11 / s10 5g입니다)

.crt파일 그대로 설치시도 결과동일

**Comment by rootadminaccess** [comment]
해결했습니다.
![1620661532724.jpg](https://user-images.githubusercontent.com/72973521/117687090-6767f400-b1f2-11eb-9402-1360c598199b.jpg)
![1620661534832-0.jpg](https://user-images.githubusercontent.com/72973521/117687110-6afb7b00-b1f2-11eb-8cf1-fbae3dee1fd8.jpg)![1620661534832-1.jpg](https://user-images.githubusercontent.com/72973521/117687117-6c2ca800-b1f2-11eb-829d-3377a3edb3db.jpg)


해결방법 공유드립니다.
안드로이드 보안패치 이후로 브라우져에서 바로 인증서 설치가 안되네요. 다운받은 인증서의 확장자를 .cer 로 바꾸어주시고
수동인증서 설치로 적용해주세요.
수동인증서설치시 인증서 이름란은 자유롭게 적으시면됩니다.

***
http://burp 는 버프슈트 이용시 인증서설치
http://private.mail 은 izpm.wonyoung.kr  포트 1029 프록시 이용시 인증서 설치 사이트입니다.
***
