### ISSUE TITLE
http://izpm.wonyoung.kr/ 접속시 리캡챠 관련한 오류가 뜹니다.

### ISSUE THREAD

**Issue by kimty0** [mdsnins/IZPM-Backup#2]
현재(3월 15일 오후 1시 13분 기준) 위 페이지 접속 시 우측 하단에 "사이트 소유자가 확인해야 하는 오류 메시지: 사이트 키가 올바르지 않습니다." 라는 리캡챠 오류가 뜨고, 스크립트 다운이 되지 않고 있습니다.
접속한 환경은 Chrome, IE 두가지 환경에서 테스트 진행했으며, 특이사항으론, 크롬 개발자도구의 콘솔에서는 특별한 에러메시지가 노출되지 않았습니다.

그리고 다시한번 이런 프로그램과 서버 구축해주셔서 감사합니다.

**Comment by mdsnins** [comment]
1시쯤부터 서버 메모리 부족으로 여러 불편한 상황이 많았습니다. 곧 조치하여 다시 오픈할 예정입니다.
