### ISSUE TITLE
날짜 기준 19년 5월 9일 이전 메일은 오류가 발생했습니다. 라고 저장되었네요.

### ISSUE THREAD

**Issue by kimty0** [mdsnins/IZPM-Backup#3]
리캡차 관련해서는 빠르게 처리해줘서 고마워용

일단 지금 리폿하는 이슈는 저만 그런건지 아니면 다들 그런건지 케이스 체크는 필요해보입니다만,
일단 제 상황에서는 스크립트 실행해서 백업하고 난 결과를 확인해보니 19년 5월 9일 이전 프메들은 전부 '오류가 발생했습니다.' 라는 내용으로만 저장이 되었고, 이미지나 이런 부분도 깨진걸로 보입니다.

한번 다시 전체 케이스를 수행해볼 계획입니다만, 수행하는데 시간이 걸리고, 혹시라도 저 말고도 유사한 사례가 있을수 있어서 일단 이슈로 작성해놓습니다.

다시 한번 좋은 프로그램 만들어줘서 고마워용

**Comment by mdsnins** [comment]
저도 시간 나는대로 확인해보겠습니다. 특정 시점을 기준으로 API 형식이 바뀌진 않았을거고, 서버측에서 request가 잦아서 뭔가에 걸린듯 한데 한번 확인이 필요할 듯 하네요. 감사합니다.
