### ISSUE TITLE
안드로이드용 수정된 앱 설치불가

### ISSUE THREAD

**Issue by tk7661** [mdsnins/IZPM-Backup#4]
안드로이드 유저 가이드 1번에서 막힙니다...
설치가 안되는데 어떻게 해야 할까요?
기종은 노트20U 입니다

**Comment by HoyA-G** [comment]
https://sbnet.co.kr/install-apk-on-android/
글 읽어보시고 출처를 알 수 없는 앱 설치에 대한 권한 주시고 설치해보세요

**Comment by tk7661** [comment]
다운로드 게이지가 차다가 멈추고
앱이 설치되지 않았습니다 가 뜨네요

**Comment by HoyA-G** [comment]
https://drive.google.com/file/d/1LyQ8qNwXBcskSjpvawe4bNV1mXPtq7sF/view?usp=sharing
위 링크로 다운 받아보시고 안되면 PC에서 새창에 주소를 직접 치셔서 받아보세요
