### ISSUE TITLE
CA 인증서를 설치할 수 없음

### ISSUE THREAD

**Issue by der1029** [mdsnins/IZPM-Backup#6]
좋은 프로그램 만들어주셔서 감사합니다.
근데 제가 초보라 그런지 중간에 막히는 부분이 있어서.....
null 인증서가 설정에 설치되어 있어야 합니다. 신뢰할 수 있는 기관에서 발급한 CA 인증서만 설치하세요.
라고 뜨느데 해결방법이 있을까요??

**Comment by HoyA-G** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=wonyeong&no=368388
여기 설명 있어요 갤럭시 유저면 별도의 설치 과정이 필요합니다

**Comment by der1029** [comment]
덕분에 백업할 수 있었습니다 감사합니다.
